#!/bin/sh -x

#
# Copyright 1997-2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

AS_INSTALL=`dirname $0`/..
AS_INSTALL_LIB=$AS_INSTALL/modules
CONFIG_HOME=$AS_INSTALL/config
. "${CONFIG_HOME}/asenv.conf"

LD_LIBRARY_PATH="$AS_INSTALL/lib":"$LD_LIBRARY_PATH";export LD_LIBRARY_PATH

AS_JAVA=${JAVA_HOME}

"${AS_JAVA}/bin/java" -Dcom.sun.aas.installRoot="${AS_INSTALL}" -Dcom.sun.aas.utool.LogLevel="INFO" -Dcom.sun.aas.domainRoot="$AS_DEF_DOMAINS_PATH" -Dcom.sun.aas.instanceRoot="${AS_INSTALL}" -Dcom.sun.aas.configRoot="${AS_CONFIG}" -Dcom.sun.aas.java.home="$AS_JAVA" -cp "$AS_INSTALL_LIB/admin-cli.jar":"$AS_INSTALL_LIB/admin-cli.jar":"$AS_INSTALL_LIB/kernel.jar":"$AS_INSTALL_LIB/upgrade.jar"  com.sun.enterprise.tools.upgrade.UpgradeToolMain $*
