<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://endpoint/jaxws" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://endpoint/jaxws" name="HiEJBService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://endpoint/jaxws" schemaLocation="HiEJBService_schema1.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
    </xsd:schema>
  </types>
  <message name="sayHi">
    <part name="parameters" element="tns:sayHi"/>
  </message>
  <message name="sayHiResponse">
    <part name="parameters" element="tns:sayHiResponse"/>
  </message>
  <portType name="Hi">
    <operation name="sayHi">
      <input message="tns:sayHi"/>
      <output message="tns:sayHiResponse"/>
    </operation>
  </portType>
  <binding name="HiEJBPortBinding" type="tns:Hi">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="sayHi">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="HiEJBService">
    <port name="HiEJBPort" binding="tns:HiEJBPortBinding">
      <soap:address location="http://localhost:12017/HiEJBPort" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
    </port>
  </service>
</definitions>
