<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://example.com/Hello" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="HelloService" targetNamespace="http://example.com/Hello">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://example.com/Hello" schemaLocation="schema1.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
    </xsd:schema>
  </types>
  <message name="sayHello">
    <part name="parameters" element="tns:sayHello"/>
  </message>
  <message name="sayHelloResponse">
    <part name="parameters" element="tns:sayHelloResponse"/>
  </message>
  <portType name="Hello">
    <operation name="sayHello">
      <input message="tns:sayHello"/>
      <output message="tns:sayHelloResponse"/>
    </operation>
  </portType>
  <binding name="HelloBinding" type="tns:Hello">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="sayHello">
      <soap:operation soapAction="urn:SayHello"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="HelloService">
    <port name="Hello" binding="tns:HelloBinding">
      <soap:address location="http://blueprints.SFBay.Sun.COM:8080/hello/webservice/HelloService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
    </port>
  </service>
</definitions>
