ALTER TABLE CMP3_ORDER DROP CONSTRAINT FK_ORDER;
ALTER TABLE CMP3_ORDER DROP CONSTRAINT FK_ITEM;

DROP TABLE CMP3_CUSTOMER;
DROP TABLE CMP3_ITEM;
DROP TABLE CMP3_ORDER;

CREATE TABLE CMP3_CUSTOMER(CUST_ID INTEGER PRIMARY KEY NOT NULL,CUST_VERSION INTEGER,CITY VARCHAR(255),NAME VARCHAR(255));
CREATE TABLE CMP3_ITEM(ITEM_ID INTEGER PRIMARY KEY NOT NULL,ITEM_VERSION INTEGER, DESCRIPTION VARCHAR(255),NAME VARCHAR(255));
CREATE TABLE CMP3_ORDER(ORDER_ID INTEGER PRIMARY KEY NOT NULL,ORDER_VERSION INTEGER,QTY INTEGER,SHIPADD VARCHAR(255),CUST_ID INTEGER,ITEM_ID INTEGER);

ALTER TABLE CMP3_ORDER ADD CONSTRAINT FK_ORDER FOREIGN KEY (CUST_ID) REFERENCES CMP3_CUSTOMER (CUST_ID) ;
ALTER TABLE CMP3_ORDER ADD CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES CMP3_ITEM(ITEM_ID) ;
