<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://example.com/Calculator" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://example.com/Calculator" name="CalculatorService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://example.com/Calculator" schemaLocation="CalculatorService_schema1.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema>
  </types>
  <message name="add">
    <part name="part1" element="tns:number1"/>
  </message>
  <message name="addResponse">
    <part name="addResponse" element="tns:addResponse"/>
  </message>
  <message name="Exception">
    <part name="fault" element="tns:Exception"/>
  </message>
  <portType name="Calculator">
    <operation name="add">
      <input message="tns:add"/>
      <output message="tns:addResponse"/>
      <fault message="tns:Exception" name="Exception"/>
    </operation>
  </portType>
  <binding name="CalculatorPortBinding" type="tns:Calculator">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="add">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="Exception">
        <soap:fault name="Exception" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="CalculatorService">
    <port name="CalculatorPort" binding="tns:CalculatorPortBinding">
      <soap:address location="http://localhost:12011/calculatorendpoint"/>
    </port>
  </service>
</definitions>
