/*
 * The contents of this file are subject to the terms 
 * of the Common Development and Distribution License 
 * (the "License").  You may not use this file except 
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at 
 * glassfish/bootstrap/legal/CDDLv1.0.txt or 
 * https://glassfish.dev.java.net/public/CDDLv1.0.html. 
 * See the License for the specific language governing 
 * permissions and limitations under the License.
 * 
 * When distributing Covered Code, include this CDDL 
 * HEADER in each file and include the License file at 
 * glassfish/bootstrap/legal/CDDLv1.0.txt.  If applicable, 
 * add the following below this CDDL HEADER, with the 
 * fields enclosed by brackets "[]" replaced with your 
 * own identifying information: Portions Copyright [yyyy] 
 * [name of copyright owner]
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-1973 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.04.20 at 08:27:00 IST 
//


package com.sun.persistence.api.deployment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sun.persistence.api.deployment.DescriptorNode;
import com.sun.persistence.api.deployment.DiscriminatorColumnDescriptor;
import com.sun.persistence.api.deployment.EmbeddableDescriptor;
import com.sun.persistence.api.deployment.EntityDescriptor;
import com.sun.persistence.api.deployment.GeneratedIdTableDescriptor;
import com.sun.persistence.api.deployment.InheritanceDescriptor;
import com.sun.persistence.api.deployment.InheritanceJoinColumnDescriptor;
import com.sun.persistence.api.deployment.JoinColumnDescriptor;
import com.sun.persistence.api.deployment.NamedQueryDescriptor;
import com.sun.persistence.api.deployment.PropertyDescriptor;
import com.sun.persistence.api.deployment.SecondaryTableDescriptor;
import com.sun.persistence.api.deployment.SequenceGeneratorDescriptor;
import com.sun.persistence.api.deployment.TableDescriptor;
import com.sun.persistence.api.deployment.TableGeneratorDescriptor;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "class", namespace = "http://java.sun.com/xml/ns/persistence_ORM")
public class ClassDescriptor
    extends DescriptorNode
{

    @XmlElement(name = "entity", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = EntityDescriptor.class)
    protected EntityDescriptor entity;
    @XmlElement(name = "named-query", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = NamedQueryDescriptor.class)
    protected List<NamedQueryDescriptor> namedQuery;
    @XmlElement(name = "table", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = TableDescriptor.class)
    protected TableDescriptor table;
    @XmlElement(name = "secondary-table", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = SecondaryTableDescriptor.class)
    protected List<SecondaryTableDescriptor> secondaryTable;
    @XmlElement(name = "join-column", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = JoinColumnDescriptor.class)
    protected List<JoinColumnDescriptor> joinColumn;
    @XmlElement(name = "inheritance", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = InheritanceDescriptor.class)
    protected InheritanceDescriptor inheritance;
    @XmlElement(name = "inheritance-join-column", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = InheritanceJoinColumnDescriptor.class)
    protected List<InheritanceJoinColumnDescriptor> inheritanceJoinColumn;
    @XmlElement(name = "discriminator-column", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = DiscriminatorColumnDescriptor.class)
    protected DiscriminatorColumnDescriptor discriminatorColumn;
    @XmlElement(name = "embeddable", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = EmbeddableDescriptor.class)
    protected EmbeddableDescriptor embeddable;
    @XmlElement(name = "generated-id-table", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = GeneratedIdTableDescriptor.class)
    protected GeneratedIdTableDescriptor generatedIdTable;
    @XmlElement(name = "sequence-generator", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = SequenceGeneratorDescriptor.class)
    protected SequenceGeneratorDescriptor sequenceGenerator;
    @XmlElement(name = "table-generator", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = TableGeneratorDescriptor.class)
    protected TableGeneratorDescriptor tableGenerator;
    @XmlElement(name = "property", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = PropertyDescriptor.class)
    protected List<PropertyDescriptor> property;
    @XmlAttribute(name = "name", namespace = "")
    protected String name;

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.EntityDescriptor}
     */
    public EntityDescriptor getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.EntityDescriptor}
     */
    public void setEntity(EntityDescriptor value) {
        this.entity = value;
    }

    public boolean isSetEntity() {
        return (this.entity!= null);
    }

    public void unsetEntity() {
        this.entity = null;
    }

    protected List<NamedQueryDescriptor> _getNamedQuery() {
        if (namedQuery == null) {
            namedQuery = new ArrayList<NamedQueryDescriptor>();
        }
        return namedQuery;
    }

    /**
     * Gets the value of the namedQuery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namedQuery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamedQuery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.NamedQueryDescriptor}
     * 
     */
    public List<NamedQueryDescriptor> getNamedQuery() {
        return this._getNamedQuery();
    }

    public boolean isSetNamedQuery() {
        return (this.namedQuery!= null);
    }

    public void unsetNamedQuery() {
        this.namedQuery = null;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.TableDescriptor}
     */
    public TableDescriptor getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.TableDescriptor}
     */
    public void setTable(TableDescriptor value) {
        this.table = value;
    }

    public boolean isSetTable() {
        return (this.table!= null);
    }

    public void unsetTable() {
        this.table = null;
    }

    protected List<SecondaryTableDescriptor> _getSecondaryTable() {
        if (secondaryTable == null) {
            secondaryTable = new ArrayList<SecondaryTableDescriptor>();
        }
        return secondaryTable;
    }

    /**
     * Gets the value of the secondaryTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondaryTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecondaryTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.SecondaryTableDescriptor}
     * 
     */
    public List<SecondaryTableDescriptor> getSecondaryTable() {
        return this._getSecondaryTable();
    }

    public boolean isSetSecondaryTable() {
        return (this.secondaryTable!= null);
    }

    public void unsetSecondaryTable() {
        this.secondaryTable = null;
    }

    protected List<JoinColumnDescriptor> _getJoinColumn() {
        if (joinColumn == null) {
            joinColumn = new ArrayList<JoinColumnDescriptor>();
        }
        return joinColumn;
    }

    /**
     * Gets the value of the joinColumn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the joinColumn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJoinColumn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.JoinColumnDescriptor}
     * 
     */
    public List<JoinColumnDescriptor> getJoinColumn() {
        return this._getJoinColumn();
    }

    public boolean isSetJoinColumn() {
        return (this.joinColumn!= null);
    }

    public void unsetJoinColumn() {
        this.joinColumn = null;
    }

    /**
     * Gets the value of the inheritance property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.InheritanceDescriptor}
     */
    public InheritanceDescriptor getInheritance() {
        return inheritance;
    }

    /**
     * Sets the value of the inheritance property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.InheritanceDescriptor}
     */
    public void setInheritance(InheritanceDescriptor value) {
        this.inheritance = value;
    }

    public boolean isSetInheritance() {
        return (this.inheritance!= null);
    }

    public void unsetInheritance() {
        this.inheritance = null;
    }

    protected List<InheritanceJoinColumnDescriptor> _getInheritanceJoinColumn() {
        if (inheritanceJoinColumn == null) {
            inheritanceJoinColumn = new ArrayList<InheritanceJoinColumnDescriptor>();
        }
        return inheritanceJoinColumn;
    }

    /**
     * Gets the value of the inheritanceJoinColumn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inheritanceJoinColumn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInheritanceJoinColumn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.InheritanceJoinColumnDescriptor}
     * 
     */
    public List<InheritanceJoinColumnDescriptor> getInheritanceJoinColumn() {
        return this._getInheritanceJoinColumn();
    }

    public boolean isSetInheritanceJoinColumn() {
        return (this.inheritanceJoinColumn!= null);
    }

    public void unsetInheritanceJoinColumn() {
        this.inheritanceJoinColumn = null;
    }

    /**
     * Gets the value of the discriminatorColumn property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.DiscriminatorColumnDescriptor}
     */
    public DiscriminatorColumnDescriptor getDiscriminatorColumn() {
        return discriminatorColumn;
    }

    /**
     * Sets the value of the discriminatorColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.DiscriminatorColumnDescriptor}
     */
    public void setDiscriminatorColumn(DiscriminatorColumnDescriptor value) {
        this.discriminatorColumn = value;
    }

    public boolean isSetDiscriminatorColumn() {
        return (this.discriminatorColumn!= null);
    }

    public void unsetDiscriminatorColumn() {
        this.discriminatorColumn = null;
    }

    /**
     * Gets the value of the embeddable property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.EmbeddableDescriptor}
     */
    public EmbeddableDescriptor getEmbeddable() {
        return embeddable;
    }

    /**
     * Sets the value of the embeddable property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.EmbeddableDescriptor}
     */
    public void setEmbeddable(EmbeddableDescriptor value) {
        this.embeddable = value;
    }

    public boolean isSetEmbeddable() {
        return (this.embeddable!= null);
    }

    public void unsetEmbeddable() {
        this.embeddable = null;
    }

    /**
     * Gets the value of the generatedIdTable property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.GeneratedIdTableDescriptor}
     */
    public GeneratedIdTableDescriptor getGeneratedIdTable() {
        return generatedIdTable;
    }

    /**
     * Sets the value of the generatedIdTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.GeneratedIdTableDescriptor}
     */
    public void setGeneratedIdTable(GeneratedIdTableDescriptor value) {
        this.generatedIdTable = value;
    }

    public boolean isSetGeneratedIdTable() {
        return (this.generatedIdTable!= null);
    }

    public void unsetGeneratedIdTable() {
        this.generatedIdTable = null;
    }

    /**
     * Gets the value of the sequenceGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.SequenceGeneratorDescriptor}
     */
    public SequenceGeneratorDescriptor getSequenceGenerator() {
        return sequenceGenerator;
    }

    /**
     * Sets the value of the sequenceGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.SequenceGeneratorDescriptor}
     */
    public void setSequenceGenerator(SequenceGeneratorDescriptor value) {
        this.sequenceGenerator = value;
    }

    public boolean isSetSequenceGenerator() {
        return (this.sequenceGenerator!= null);
    }

    public void unsetSequenceGenerator() {
        this.sequenceGenerator = null;
    }

    /**
     * Gets the value of the tableGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link com.sun.persistence.api.deployment.TableGeneratorDescriptor}
     */
    public TableGeneratorDescriptor getTableGenerator() {
        return tableGenerator;
    }

    /**
     * Sets the value of the tableGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sun.persistence.api.deployment.TableGeneratorDescriptor}
     */
    public void setTableGenerator(TableGeneratorDescriptor value) {
        this.tableGenerator = value;
    }

    public boolean isSetTableGenerator() {
        return (this.tableGenerator!= null);
    }

    public void unsetTableGenerator() {
        this.tableGenerator = null;
    }

    protected List<PropertyDescriptor> _getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyDescriptor>();
        }
        return property;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.PropertyDescriptor}
     * 
     */
    public List<PropertyDescriptor> getProperty() {
        return this._getProperty();
    }

    public boolean isSetProperty() {
        return (this.property!= null);
    }

    public void unsetProperty() {
        this.property = null;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    public void unsetName() {
        this.name = null;
    }

}
