/*
 * The contents of this file are subject to the terms 
 * of the Common Development and Distribution License 
 * (the "License").  You may not use this file except 
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at 
 * glassfish/bootstrap/legal/CDDLv1.0.txt or 
 * https://glassfish.dev.java.net/public/CDDLv1.0.html. 
 * See the License for the specific language governing 
 * permissions and limitations under the License.
 * 
 * When distributing Covered Code, include this CDDL 
 * HEADER in each file and include the License file at 
 * glassfish/bootstrap/legal/CDDLv1.0.txt.  If applicable, 
 * add the following below this CDDL HEADER, with the 
 * fields enclosed by brackets "[]" replaced with your 
 * own identifying information: Portions Copyright [yyyy] 
 * [name of copyright owner]
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-1973 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.04.20 at 08:27:00 IST 
//


package com.sun.persistence.api.deployment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sun.persistence.api.deployment.JoinColumnDescriptor;
import com.sun.persistence.api.deployment.TableDescriptor;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "secondary-table", namespace = "http://java.sun.com/xml/ns/persistence_ORM")
public class SecondaryTableDescriptor
    extends TableDescriptor
{

    @XmlElement(name = "join", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = JoinColumnDescriptor.class)
    protected List<JoinColumnDescriptor> join;

    protected List<JoinColumnDescriptor> _getJoin() {
        if (join == null) {
            join = new ArrayList<JoinColumnDescriptor>();
        }
        return join;
    }

    /**
     * Gets the value of the join property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the join property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJoin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.JoinColumnDescriptor}
     * 
     */
    public List<JoinColumnDescriptor> getJoin() {
        return this._getJoin();
    }

    public boolean isSetJoin() {
        return (this.join!= null);
    }

    public void unsetJoin() {
        this.join = null;
    }

}
