/*
 * The contents of this file are subject to the terms 
 * of the Common Development and Distribution License 
 * (the "License").  You may not use this file except 
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at 
 * glassfish/bootstrap/legal/CDDLv1.0.txt or 
 * https://glassfish.dev.java.net/public/CDDLv1.0.html. 
 * See the License for the specific language governing 
 * permissions and limitations under the License.
 * 
 * When distributing Covered Code, include this CDDL 
 * HEADER in each file and include the License file at 
 * glassfish/bootstrap/legal/CDDLv1.0.txt.  If applicable, 
 * add the following below this CDDL HEADER, with the 
 * fields enclosed by brackets "[]" replaced with your 
 * own identifying information: Portions Copyright [yyyy] 
 * [name of copyright owner]
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-1973 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.04.20 at 08:27:00 IST 
//


package com.sun.persistence.api.deployment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sun.persistence.api.deployment.DescriptorNode;
import com.sun.persistence.api.deployment.UniqueConstraintDescriptor;

@XmlAccessorType(value = AccessType.FIELD)
@XmlType(name = "table", namespace = "http://java.sun.com/xml/ns/persistence_ORM")
public class TableDescriptor
    extends DescriptorNode
{

    @XmlElement(defaultValue = "", name = "name", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = String.class)
    protected String name;
    @XmlElement(defaultValue = "", name = "catalog", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = String.class)
    protected String catalog;
    @XmlElement(defaultValue = "", name = "schema", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = String.class)
    protected String schema;
    @XmlElement(name = "unique-constraint", namespace = "http://java.sun.com/xml/ns/persistence_ORM", type = UniqueConstraintDescriptor.class)
    protected List<UniqueConstraintDescriptor> uniqueConstraint;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    public void unsetName() {
        this.name = null;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setCatalog(String value) {
        this.catalog = value;
    }

    public boolean isSetCatalog() {
        return (this.catalog!= null);
    }

    public void unsetCatalog() {
        this.catalog = null;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    public boolean isSetSchema() {
        return (this.schema!= null);
    }

    public void unsetSchema() {
        this.schema = null;
    }

    protected List<UniqueConstraintDescriptor> _getUniqueConstraint() {
        if (uniqueConstraint == null) {
            uniqueConstraint = new ArrayList<UniqueConstraintDescriptor>();
        }
        return uniqueConstraint;
    }

    /**
     * Gets the value of the uniqueConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.sun.persistence.api.deployment.UniqueConstraintDescriptor}
     * 
     */
    public List<UniqueConstraintDescriptor> getUniqueConstraint() {
        return this._getUniqueConstraint();
    }

    public boolean isSetUniqueConstraint() {
        return (this.uniqueConstraint!= null);
    }

    public void unsetUniqueConstraint() {
        this.uniqueConstraint = null;
    }

}
