DROP TABLE COMPOSITEINTSTRINGBEANTABLE
go

CREATE TABLE COMPOSITEINTSTRINGBEANTABLE (
	ID     INTEGER, 
	NAME   VARCHAR(255), 
	SALARY DOUBLE PRECISION NOT NULL, 
	CONSTRAINT PK_COMPOSITEINTSTRINGBEANTABL PRIMARY KEY (ID, NAME)
)

go

