DROP TABLE Customer;
DROP TABLE Item;

CREATE TABLE Customer 
(
	CUSTOMER_ID VARCHAR(255) PRIMARY KEY, 
	name VARCHAR(255)  
);


CREATE TABLE Item 
(
	item_Id VARCHAR(255) PRIMARY KEY, 
	name VARCHAR(255) ,
	price DOUBLE PRECISION NOT NULL ,
	CUSTOMER_ID VARCHAR(255) ,
	FOREIGN KEY (CUSTOMER_ID)   REFERENCES Customer (CUSTOMER_ID)
);


