package org.glassfish.enterprise.admin.ncli;

import org.glassfish.enterprise.admin.ncli.metadata.CommandDesc;
import org.glassfish.enterprise.admin.ncli.comm.TargetServer;

import java.util.Collections;
import java.util.List;

/** Represents a command class. The goal of the command line parser is to build a command. If the command
 *  can not be built, it is a syntax error. A command comprises of a list of options and a list of operands.
 *  Once a command is built, it is executed on a given server. It is possible that such a command can be executed
 *  locally, but that is not required for this release. Eventually, all commands, local and remote should be
 *  represented by instances of this class.
 *  <p>
 *  &lt;lament> As of now, the world of local and remote commands looks so different! This
 *  difference has to be eliminated. &lt;lament> 
 * <p>
 * Instances of this class are immutable. Since the metadata classes (generated by JAXB) are mutable, this class
 * provides no way to reach the command's metadata or the metadata of the options and operands. Arguably, it can still
 * be said that the state of this command can be modified because the callers can advertently or inadvertently change
 * the metadata passed into the constructor of this class. Callers should be aware of that.
 * <p>
 * This is a package private class.
 * @author &#2325;&#2375;&#2342;&#2366;&#2352 (km@dev.java.net)
 * @see Option
 * @see Operand
 * @see org.glassfish.enterprise.admin.ncli.metadata.OptionDesc
 * @see CommandDesc
 */
final class NewCommand {
    private final CommandDesc cmdMetadata;
    private final List<Option> options;
    private final List<Operand> operands;

    /** The only constructor that creates an immutable instance of this class.
     *  None of the parameters should be null.
     * @param cmdMetadata CommandDesc representing metadata of the command, may not be null
     * @param options A set of Options of this command, may not be null
     * @param operands A set of Operands of this command, may not be null
     * @throws IllegalArgumentException if any of the parameters are null
     */
    NewCommand(CommandDesc cmdMetadata, List<Option> options, List<Operand> operands) {
        if (cmdMetadata == null || options == null || operands == null)
            throw new IllegalArgumentException("null command metadata, options or operands");
        this.cmdMetadata = cmdMetadata;
        if (cmdMetadata.getName() == null)
            throw new IllegalArgumentException("null name from a non-null metadata"); //should really be an assertion
        this.options     = Collections.unmodifiableList(options);
        this.operands    = Collections.unmodifiableList(operands);
    }

    /** Returns the result of command execution. This method is the essence of this class. It communicates with the
     *  given server and runs this command. Command execution return value, exceptions if any, exit code are communicated
     *  via returned result.
     *
     * @param ts TargetServer instance, may not be null
     * @return result of command execution
     */
    CommandExecutionResult execute(TargetServer ts) {
        if (ts == null)
                throw new IllegalArgumentException("null arg");
        //TODO
        //this is where it creates the request,  communicates with the server and handles the response
        return null;   
    }

    /** Returns the name of the command.
     *
     * @return String representing the name of the command. Never returns a null
     */
    String getName() {
        return cmdMetadata.getName();
    }

    /** Returns an <i> unmodifiable view </i> of the instances of Option that this command has, as specified on
     *  command line. If a user does not specify on command line any of the options that a command has, this set will be empty.
     *  Since the instances of Option returned are immutable, the returned list will never result in change to the state
     *   of this instance of NewCommand.
     * @return an unmodifiable Set of command's options. Never returns a null
     */
    List<Option> getOptions() {
        return options;
    }

    /** Returns an <i> unmodifiable view </i> of command operands, as a list. Since the operands themselves are immutable,
     *  the returned list does not change the state of this instance of NewCommand.
     *
     * @return an unmodifiable list of command's operands. Never returns a null
     */
    List<Operand> getOperands() {
        return operands;
    }

    /** A convenience method that provides a way to get an explicitly specified option with given name. Note that this
     *  method does not deal with the command's metadata, it looks only at explicitly specified option.
     *
     * @param name String representing the <i> name </i> of an option, may not be null
     * @return the Option if specified on command line, null otherwise
     * @throws NullPointerException, if the parameter is null
     */
    Option getExplicitOptionNamed(String name) {
        for(Option opt : options) {
            if (opt.getName().equals(name))
                return opt;
        }
        return null;
    }
}
