#!/bin/sh

#
# Copyright 1997-2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

AS_INSTALL=`dirname $0`/..
AS_INSTALL_LIB=$AS_INSTALL/modules

java -cp "$AS_INSTALL_LIB/webservices.jar:$AS_INSTALL_LIB/jaxb.jar" com.sun.tools.ws.WsGen "$@"