DROP TABLE D;
DROP TABLE C;
DROP TABLE B;
DROP TABLE A;


CREATE TABLE A
(
    ID     INT          PRIMARY KEY,
    LASTNAME  VARCHAR(32) NULL,
    FIRSTNAME VARCHAR(32) NULL,
    HIREDATE  DATE         NULL,
    BIRTHDATE DATE         NULL,
    SALARY    FLOAT        NOT NULL
) ENGINE=INNODB;

CREATE TABLE B
(
    ID DATE          PRIMARY KEY,
    NAME   VARCHAR(32) NULL
) ENGINE=INNODB;

CREATE TABLE C
(
    ID INT          PRIMARY KEY,
    NAME   VARCHAR(32) NULL
) ENGINE=INNODB;

commit;

quit;
