#!/bin/sh

GLASSFISH_HOME=${GLASSFISH_HOME:-"/opt/glassfishvm/glassfish3"}

case "$1" in
start)
    if [ ! -e /etc/opt/glassfishvm/image_name ]; then
        echo "Image not configured, glassfish startup exiting"
        return
    fi
    image_name=`cat /etc/opt/glassfishvm/image_name`
    node_name=`echo $image_name\_node`
    das_ip=`cat /etc/opt/glassfishvm/das_info`
	das_port=`cat /etc/opt/glassfishvm/das_port`
# reset networking interfaces on first boot. 
	if [ ! -e /etc/opt/glassfishvm/initial_config_done ]; then
  		/opt/glassfishvm/bin/initial-setup.sh
    fi
# get the IP address of this instance
    intf=`awk < /proc/net/dev '
    {   if ($1 ~ /^eth/) {
            split($1,field, ":")

            print(field[1])
        }
    }'`
    ip_address=`/sbin/ifconfig $intf  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`

	if [ ! -e /etc/opt/glassfishvm/initial_config_done ]; then
# first time boot, we declare ourselves to the DAS as a new node and a new instance
		cluster_name=`cat /etc/opt/glassfishvm/cluster_info`
		ip_address=`/sbin/ifconfig $intf  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
		echo $ip_address >/etc/opt/glassfishvm/configured_ip
#		$GLASSFISH_HOME/glassfish//bin/asadmin -H $das_ip -p $das_port create-local-instance --node $ip_address --cluster $cluster_name --nodedir $GLASSFISH_HOME $image_name
		$GLASSFISH_HOME/glassfish/bin/asadmin -H $das_ip -p $das_port create-node-ssh --nodehost $ip_address --installdir $GLASSFISH_HOME $node_name
		$GLASSFISH_HOME/glassfish/bin/asadmin -H $das_ip -p $das_port create-instance --node $node_name --cluster $cluster_name $image_name
  		touch /etc/opt/glassfishvm/initial_config_done
		return
    else
# we must check that our IP address has not changed since the last time we booted.
        configured_ip_address=`cat /etc/opt/glassfishvm/configured_ip`
        if [ $ip_address != $configured_ip_address ]; then
            echo "IP address changed from $configured_ip_address to $ip_address"
		    $GLASSFISH_HOME/glassfish/bin/asadmin -H $das_ip -p $das_port update-node-ssh --nodehost $ip_address $node_name
    		echo $ip_address >/etc/opt/glassfishvm/configured_ip
        else
            echo "Unchanged IP address at $ip_address"
        fi
	fi
#    we don't startup glassfish automatically as we rely on the DAS.
    $GLASSFISH_HOME/glassfish/bin/asadmin start-domain >/dev/null
    ;;
stop)
    $GLASSFISH_HOME/glassfish/bin/asadmin stop-domain >/dev/null
    ;;
restart)
    $GLASSFISH_HOME/glassfish/bin/asadmin restart-domain >/dev/null
    ;;
*)
    echo "usage: $0 (start|stop|restart|help)"
esac


