
package cascadeDelete;

import javax.ejb.*;

/**
 * Created Dec 23, 2002 12:43:09 PM
 * Code generated by the Forte For Java EJB Builder
 * @author mvatkina
 */

public interface LocalAHome extends javax.ejb.EJBLocalHome {
    
    public cascadeDelete.LocalA findByPrimaryKey(java.lang.Integer aKey)
    throws javax.ejb.FinderException;
    
    public java.util.Collection findAll() throws javax.ejb.FinderException;
    
}
