/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://oss.oracle.com/licenses/CDDL+GPL-1.1
 * or LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA-R26)

package com.sun.s1asdev.ejb.classload.lifecycle;


public class GoogleSearchResult {
    protected boolean documentFiltering;
    protected java.lang.String searchComments;
    protected int estimatedTotalResultsCount;
    protected boolean estimateIsExact;
    protected com.sun.s1asdev.ejb.classload.lifecycle.ResultElement[] resultElements;
    protected java.lang.String searchQuery;
    protected int startIndex;
    protected int endIndex;
    protected java.lang.String searchTips;
    protected com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory[] directoryCategories;
    protected double searchTime;
    
    public GoogleSearchResult() {
    }
    
    public GoogleSearchResult(boolean documentFiltering, java.lang.String searchComments, int estimatedTotalResultsCount, boolean estimateIsExact, com.sun.s1asdev.ejb.classload.lifecycle.ResultElement[] resultElements, java.lang.String searchQuery, int startIndex, int endIndex, java.lang.String searchTips, com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory[] directoryCategories, double searchTime) {
        this.documentFiltering = documentFiltering;
        this.searchComments = searchComments;
        this.estimatedTotalResultsCount = estimatedTotalResultsCount;
        this.estimateIsExact = estimateIsExact;
        this.resultElements = resultElements;
        this.searchQuery = searchQuery;
        this.startIndex = startIndex;
        this.endIndex = endIndex;
        this.searchTips = searchTips;
        this.directoryCategories = directoryCategories;
        this.searchTime = searchTime;
    }
    
    public boolean isDocumentFiltering() {
        return documentFiltering;
    }
    
    public void setDocumentFiltering(boolean documentFiltering) {
        this.documentFiltering = documentFiltering;
    }
    
    public java.lang.String getSearchComments() {
        return searchComments;
    }
    
    public void setSearchComments(java.lang.String searchComments) {
        this.searchComments = searchComments;
    }
    
    public int getEstimatedTotalResultsCount() {
        return estimatedTotalResultsCount;
    }
    
    public void setEstimatedTotalResultsCount(int estimatedTotalResultsCount) {
        this.estimatedTotalResultsCount = estimatedTotalResultsCount;
    }
    
    public boolean isEstimateIsExact() {
        return estimateIsExact;
    }
    
    public void setEstimateIsExact(boolean estimateIsExact) {
        this.estimateIsExact = estimateIsExact;
    }
    
    public com.sun.s1asdev.ejb.classload.lifecycle.ResultElement[] getResultElements() {
        return resultElements;
    }
    
    public void setResultElements(com.sun.s1asdev.ejb.classload.lifecycle.ResultElement[] resultElements) {
        this.resultElements = resultElements;
    }
    
    public java.lang.String getSearchQuery() {
        return searchQuery;
    }
    
    public void setSearchQuery(java.lang.String searchQuery) {
        this.searchQuery = searchQuery;
    }
    
    public int getStartIndex() {
        return startIndex;
    }
    
    public void setStartIndex(int startIndex) {
        this.startIndex = startIndex;
    }
    
    public int getEndIndex() {
        return endIndex;
    }
    
    public void setEndIndex(int endIndex) {
        this.endIndex = endIndex;
    }
    
    public java.lang.String getSearchTips() {
        return searchTips;
    }
    
    public void setSearchTips(java.lang.String searchTips) {
        this.searchTips = searchTips;
    }
    
    public com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory[] getDirectoryCategories() {
        return directoryCategories;
    }
    
    public void setDirectoryCategories(com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory[] directoryCategories) {
        this.directoryCategories = directoryCategories;
    }
    
    public double getSearchTime() {
        return searchTime;
    }
    
    public void setSearchTime(double searchTime) {
        this.searchTime = searchTime;
    }
}
