/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://oss.oracle.com/licenses/CDDL+GPL-1.1
 * or LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA-R26)

package com.sun.s1asdev.ejb.classload.lifecycle;


public class ResultElement {
    protected java.lang.String summary;
    protected java.lang.String URL;
    protected java.lang.String snippet;
    protected java.lang.String title;
    protected java.lang.String cachedSize;
    protected boolean relatedInformationPresent;
    protected java.lang.String hostName;
    protected com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory directoryCategory;
    protected java.lang.String directoryTitle;
    
    public ResultElement() {
    }
    
    public ResultElement(java.lang.String summary, java.lang.String URL, java.lang.String snippet, java.lang.String title, java.lang.String cachedSize, boolean relatedInformationPresent, java.lang.String hostName, com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory directoryCategory, java.lang.String directoryTitle) {
        this.summary = summary;
        this.URL = URL;
        this.snippet = snippet;
        this.title = title;
        this.cachedSize = cachedSize;
        this.relatedInformationPresent = relatedInformationPresent;
        this.hostName = hostName;
        this.directoryCategory = directoryCategory;
        this.directoryTitle = directoryTitle;
    }
    
    public java.lang.String getSummary() {
        return summary;
    }
    
    public void setSummary(java.lang.String summary) {
        this.summary = summary;
    }
    
    public java.lang.String getURL() {
        return URL;
    }
    
    public void setURL(java.lang.String URL) {
        this.URL = URL;
    }
    
    public java.lang.String getSnippet() {
        return snippet;
    }
    
    public void setSnippet(java.lang.String snippet) {
        this.snippet = snippet;
    }
    
    public java.lang.String getTitle() {
        return title;
    }
    
    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getCachedSize() {
        return cachedSize;
    }
    
    public void setCachedSize(java.lang.String cachedSize) {
        this.cachedSize = cachedSize;
    }
    
    public boolean isRelatedInformationPresent() {
        return relatedInformationPresent;
    }
    
    public void setRelatedInformationPresent(boolean relatedInformationPresent) {
        this.relatedInformationPresent = relatedInformationPresent;
    }
    
    public java.lang.String getHostName() {
        return hostName;
    }
    
    public void setHostName(java.lang.String hostName) {
        this.hostName = hostName;
    }
    
    public com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory getDirectoryCategory() {
        return directoryCategory;
    }
    
    public void setDirectoryCategory(com.sun.s1asdev.ejb.classload.lifecycle.DirectoryCategory directoryCategory) {
        this.directoryCategory = directoryCategory;
    }
    
    public java.lang.String getDirectoryTitle() {
        return directoryTitle;
    }
    
    public void setDirectoryTitle(java.lang.String directoryTitle) {
        this.directoryTitle = directoryTitle;
    }
}
