#!/bin/sh
dir=`dirname $0`
	mkdir -p $2
	for f in $1/man1/*.1; do
		${dir}/create_asadmin_manpage.pl $f $2;
		cat $1/shadow-template | sed -e "s/%%entity%%/`basename $f .1`-1as/" -e "s/%%target%%/asadmin-`basename $f .1`.1as/" > $2/`basename $f .1`.1as;
	done;
	for f in $1/man8/*.1m; do
		cp -p $f $2/`basename $f .1m`.1as;
  	done

