rem set a=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\CreateNodeSshCommand.java
rem set b=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\CreateRemoteNodeCommand.java
rem set c=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\dcom\CreateNodeDcom.java
rem set d=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\dcom\UpdateNodeDcomCommand.java
rem set e=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\ValidateDcom.java
rem set f=cli\src\main\java\com\sun\enterprise\admin\cli\cluster\InstallNodeDcomCommand.java
rem set g=cli\src\main\java\com\sun\enterprise\admin\cli\cluster\NativeRemoteCommandsBase.java
rem set h=cli\src\main\java\com\sun\enterprise\admin\cli\cluster\UninstallNodeDcomCommand.java
rem set i=ssh\src\main\java\org\glassfish\cluster\ssh\util\DcomUtils.java
rem set j=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\dcom\DeleteNodeDcom.java
rem set k=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\DeleteNodeRemoteCommand.java
rem set l=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\DeleteNodeSshCommand.java

rem set a=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\NodeUtils.java
rem set b=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\SecureAdminBootstrapHelper.java
rem set c=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\ValidateDcom.java
rem set d=cli\src\main\java\com\sun\enterprise\admin\cli\cluster\InstallNodeDcomCommand.java
rem set e=cli\src\main\java\com\sun\enterprise\admin\cli\cluster\UninstallNodeDcomCommand.java
rem set f=ssh\src\main\java\org\glassfish\cluster\ssh\util\DcomUtils.java
rem set g=ssh\src\main\java\org\glassfish\cluster\ssh\util\DcomInfo.java
rem set h=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\StopInstanceCommand.java
rem set i=ssh\src\main\java\org\glassfish\cluster\ssh\connect\NodeRunnerDcom.java
set a=admin\src\main\java\com\sun\enterprise\v3\admin\cluster\NodeUtils.java
set tr=d:\gf\trunk\main\nucleus\cluster
set br=d:\gf\branches\3.1.2\cluster
