<?xml version="1.0" encoding="UTF-8"?>

<definitions name="FindInterest" targetNamespace="http://hello.org/wsdl" xmlns:tns="http://hello.org/wsdl" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types/>
  <message name="InterestIF_calculateInterest">
    <part name="double_1" type="xsd:double"/>
    <part name="double_2" type="xsd:double"/></message>
  <message name="InterestIF_calculateInterestResponse">
    <part name="result" type="xsd:double"/></message>
  <portType name="InterestIF">
    <operation name="calculateInterest" parameterOrder="double_1 double_2">
      <input message="tns:InterestIF_calculateInterest"/>
      <output message="tns:InterestIF_calculateInterestResponse"/></operation></portType>
  <binding name="InterestIFBinding" type="tns:InterestIF">
    <operation name="calculateInterest">
      <input>
        <soap:body  use="literal" namespace="http://hello.org/wsdl"/></input>
      <output>
        <soap:body  use="literal" namespace="http://hello.org/wsdl"/></output>
      <soap:operation soapAction=""/></operation>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/></binding>
  <service name="FindInterest">
    <port name="InterestIFPort" binding="tns:InterestIFBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_ADDRESS"/></port></service></definitions>
