/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License.  You can
 * obtain a copy of the License at
 * https://oss.oracle.com/licenses/CDDL+GPL-1.1
 * or LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at LICENSE.txt.
 *
 * GPL Classpath Exception:
 * Oracle designates this particular file as subject to the "Classpath"
 * exception as provided by Oracle in the GPL Version 2 section of the License
 * file that accompanied this code.
 *
 * Modifications:
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyright [year] [name of copyright owner]"
 *
 * Contributor(s):
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA-R26)

package com.sun.s1asdev.ejb.classload.lifecycle;


public class GoogleSearchPort_doGoogleSearch_RequestStruct {
    protected java.lang.String key;
    protected java.lang.String q;
    protected int start;
    protected int maxResults;
    protected boolean filter;
    protected java.lang.String restrict;
    protected boolean safeSearch;
    protected java.lang.String lr;
    protected java.lang.String ie;
    protected java.lang.String oe;
    
    public GoogleSearchPort_doGoogleSearch_RequestStruct() {
    }
    
    public GoogleSearchPort_doGoogleSearch_RequestStruct(java.lang.String key, java.lang.String q, int start, int maxResults, boolean filter, java.lang.String restrict, boolean safeSearch, java.lang.String lr, java.lang.String ie, java.lang.String oe) {
        this.key = key;
        this.q = q;
        this.start = start;
        this.maxResults = maxResults;
        this.filter = filter;
        this.restrict = restrict;
        this.safeSearch = safeSearch;
        this.lr = lr;
        this.ie = ie;
        this.oe = oe;
    }
    
    public java.lang.String getKey() {
        return key;
    }
    
    public void setKey(java.lang.String key) {
        this.key = key;
    }
    
    public java.lang.String getQ() {
        return q;
    }
    
    public void setQ(java.lang.String q) {
        this.q = q;
    }
    
    public int getStart() {
        return start;
    }
    
    public void setStart(int start) {
        this.start = start;
    }
    
    public int getMaxResults() {
        return maxResults;
    }
    
    public void setMaxResults(int maxResults) {
        this.maxResults = maxResults;
    }
    
    public boolean isFilter() {
        return filter;
    }
    
    public void setFilter(boolean filter) {
        this.filter = filter;
    }
    
    public java.lang.String getRestrict() {
        return restrict;
    }
    
    public void setRestrict(java.lang.String restrict) {
        this.restrict = restrict;
    }
    
    public boolean isSafeSearch() {
        return safeSearch;
    }
    
    public void setSafeSearch(boolean safeSearch) {
        this.safeSearch = safeSearch;
    }
    
    public java.lang.String getLr() {
        return lr;
    }
    
    public void setLr(java.lang.String lr) {
        this.lr = lr;
    }
    
    public java.lang.String getIe() {
        return ie;
    }
    
    public void setIe(java.lang.String ie) {
        this.ie = ie;
    }
    
    public java.lang.String getOe() {
        return oe;
    }
    
    public void setOe(java.lang.String oe) {
        this.oe = oe;
    }
}
