// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build EA-R26)

package com.sun.s1asdev.ejb.classload.lifecycle;


public class GoogleSearchPort_doGoogleSearch_ResponseStruct {
    protected com.sun.s1asdev.ejb.classload.lifecycle.GoogleSearchResult _return;
    
    public GoogleSearchPort_doGoogleSearch_ResponseStruct() {
    }
    
    public GoogleSearchPort_doGoogleSearch_ResponseStruct(com.sun.s1asdev.ejb.classload.lifecycle.GoogleSearchResult _return) {
        this._return = _return;
    }
    
    public com.sun.s1asdev.ejb.classload.lifecycle.GoogleSearchResult get_return() {
        return _return;
    }
    
    public void set_return(com.sun.s1asdev.ejb.classload.lifecycle.GoogleSearchResult _return) {
        this._return = _return;
    }
}
