<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://endpoint/ejb" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jms="http://sun.com/jbi/wsdl/jms10" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://endpoint/ejb" name="HelloEJBService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://endpoint/ejb" schemaLocation="HelloEJBService_schema1.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
    </xsd:schema>
  </types>
  <message name="sayHello">
    <part name="parameters" element="tns:sayHello"/>
  </message>
  <message name="sayHelloResponse">
    <part name="parameters" element="tns:sayHelloResponse"/>
  </message>
  <portType name="Hello">
    <operation name="sayHello">
      <input message="tns:sayHello"/>
      <output message="tns:sayHelloResponse"/>
    </operation>
  </portType>
  <binding name="HelloEJBJMSBinding" type="tns:Hello">
    <jms:binding desc=""/>
    <operation name="sayHello">
           <input>
               <jms:message type="TextMessage"/>
           </input>
           <output>
               <jms:message type="TextMessage" />
           </output>
    </operation>
  </binding>
  <service name="HelloEJBService">
        <port name="HelloEJBPort" binding="tns:HelloEJBJMSBinding">
      <jms:artifacts destination-name="provideroutgoingqueue"
                 endpoint-role="Consumer"
                 destination-style="Queue"
                 connection-factory-name="MyQueueConnectionFactory"
                 connection-user-name="guest"
                 connection-password="guest"
                 message-selector=""
                 time-to-live="5000"
                 reply-to=""/>
        </port>
  </service>
</definitions>
