// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/glassfish/hk2/xml/test/pbuf/pc2/PBufPrecompileChild2.proto

package org.glassfish.hk2.xml.test.pbuf.pc2;

public final class PBufPrecompileChild2OuterClass {
  private PBufPrecompileChild2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBufPrecompileChild2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool z_type = 1;</code>
     */
    boolean getZType();

    /**
     * <code>int32 btype = 2;</code>
     */
    int getBtype();

    /**
     * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
     */
    boolean hasTypes();
    /**
     * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
     */
    org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean getTypes();
    /**
     * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
     */
    org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBeanOrBuilder getTypesOrBuilder();
  }
  /**
   * Protobuf type {@code org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2}
   */
  public  static final class PBufPrecompileChild2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2)
      PBufPrecompileChild2OrBuilder {
    // Use PBufPrecompileChild2.newBuilder() to construct.
    private PBufPrecompileChild2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBufPrecompileChild2() {
      zType_ = false;
      btype_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBufPrecompileChild2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              zType_ = input.readBool();
              break;
            }
            case 16: {

              btype_ = input.readInt32();
              break;
            }
            case 26: {
              org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.Builder subBuilder = null;
              if (types_ != null) {
                subBuilder = types_.toBuilder();
              }
              types_ = input.readMessage(org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(types_);
                types_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.class, org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.Builder.class);
    }

    public static final int Z_TYPE_FIELD_NUMBER = 1;
    private boolean zType_;
    /**
     * <code>bool z_type = 1;</code>
     */
    public boolean getZType() {
      return zType_;
    }

    public static final int BTYPE_FIELD_NUMBER = 2;
    private int btype_;
    /**
     * <code>int32 btype = 2;</code>
     */
    public int getBtype() {
      return btype_;
    }

    public static final int TYPES_FIELD_NUMBER = 3;
    private org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean types_;
    /**
     * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
     */
    public boolean hasTypes() {
      return types_ != null;
    }
    /**
     * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
     */
    public org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean getTypes() {
      return types_ == null ? org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.getDefaultInstance() : types_;
    }
    /**
     * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
     */
    public org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBeanOrBuilder getTypesOrBuilder() {
      return getTypes();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (zType_ != false) {
        output.writeBool(1, zType_);
      }
      if (btype_ != 0) {
        output.writeInt32(2, btype_);
      }
      if (types_ != null) {
        output.writeMessage(3, getTypes());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (zType_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, zType_);
      }
      if (btype_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, btype_);
      }
      if (types_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTypes());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2)) {
        return super.equals(obj);
      }
      org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 other = (org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2) obj;

      boolean result = true;
      result = result && (getZType()
          == other.getZType());
      result = result && (getBtype()
          == other.getBtype());
      result = result && (hasTypes() == other.hasTypes());
      if (hasTypes()) {
        result = result && getTypes()
            .equals(other.getTypes());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + Z_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getZType());
      hash = (37 * hash) + BTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBtype();
      if (hasTypes()) {
        hash = (37 * hash) + TYPES_FIELD_NUMBER;
        hash = (53 * hash) + getTypes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2)
        org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.class, org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.Builder.class);
      }

      // Construct using org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        zType_ = false;

        btype_ = 0;

        if (typesBuilder_ == null) {
          types_ = null;
        } else {
          types_ = null;
          typesBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_descriptor;
      }

      public org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 getDefaultInstanceForType() {
        return org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.getDefaultInstance();
      }

      public org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 build() {
        org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 buildPartial() {
        org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 result = new org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2(this);
        result.zType_ = zType_;
        result.btype_ = btype_;
        if (typesBuilder_ == null) {
          result.types_ = types_;
        } else {
          result.types_ = typesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2) {
          return mergeFrom((org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 other) {
        if (other == org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2.getDefaultInstance()) return this;
        if (other.getZType() != false) {
          setZType(other.getZType());
        }
        if (other.getBtype() != 0) {
          setBtype(other.getBtype());
        }
        if (other.hasTypes()) {
          mergeTypes(other.getTypes());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean zType_ ;
      /**
       * <code>bool z_type = 1;</code>
       */
      public boolean getZType() {
        return zType_;
      }
      /**
       * <code>bool z_type = 1;</code>
       */
      public Builder setZType(boolean value) {
        
        zType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool z_type = 1;</code>
       */
      public Builder clearZType() {
        
        zType_ = false;
        onChanged();
        return this;
      }

      private int btype_ ;
      /**
       * <code>int32 btype = 2;</code>
       */
      public int getBtype() {
        return btype_;
      }
      /**
       * <code>int32 btype = 2;</code>
       */
      public Builder setBtype(int value) {
        
        btype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 btype = 2;</code>
       */
      public Builder clearBtype() {
        
        btype_ = 0;
        onChanged();
        return this;
      }

      private org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean types_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean, org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.Builder, org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBeanOrBuilder> typesBuilder_;
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public boolean hasTypes() {
        return typesBuilder_ != null || types_ != null;
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean getTypes() {
        if (typesBuilder_ == null) {
          return types_ == null ? org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.getDefaultInstance() : types_;
        } else {
          return typesBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public Builder setTypes(org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean value) {
        if (typesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          types_ = value;
          onChanged();
        } else {
          typesBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public Builder setTypes(
          org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.Builder builderForValue) {
        if (typesBuilder_ == null) {
          types_ = builderForValue.build();
          onChanged();
        } else {
          typesBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public Builder mergeTypes(org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean value) {
        if (typesBuilder_ == null) {
          if (types_ != null) {
            types_ =
              org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.newBuilder(types_).mergeFrom(value).buildPartial();
          } else {
            types_ = value;
          }
          onChanged();
        } else {
          typesBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public Builder clearTypes() {
        if (typesBuilder_ == null) {
          types_ = null;
          onChanged();
        } else {
          types_ = null;
          typesBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.Builder getTypesBuilder() {
        
        onChanged();
        return getTypesFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      public org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBeanOrBuilder getTypesOrBuilder() {
        if (typesBuilder_ != null) {
          return typesBuilder_.getMessageOrBuilder();
        } else {
          return types_ == null ?
              org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.getDefaultInstance() : types_;
        }
      }
      /**
       * <code>.org.glassfish.hk2.xml.test.pbuf.pc2.TypeBean types = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean, org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.Builder, org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBeanOrBuilder> 
          getTypesFieldBuilder() {
        if (typesBuilder_ == null) {
          typesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean, org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBean.Builder, org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.TypeBeanOrBuilder>(
                  getTypes(),
                  getParentForChildren(),
                  isClean());
          types_ = null;
        }
        return typesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2)
    }

    // @@protoc_insertion_point(class_scope:org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2)
    private static final org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2();
    }

    public static org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBufPrecompileChild2>
        PARSER = new com.google.protobuf.AbstractParser<PBufPrecompileChild2>() {
      public PBufPrecompileChild2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBufPrecompileChild2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBufPrecompileChild2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBufPrecompileChild2> getParserForType() {
      return PARSER;
    }

    public org.glassfish.hk2.xml.test.pbuf.pc2.PBufPrecompileChild2OuterClass.PBufPrecompileChild2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>org/glassfish/hk2/xml/test/pbuf/pc2/PB" +
      "ufPrecompileChild2.proto\022#org.glassfish." +
      "hk2.xml.test.pbuf.pc2\0322org/glassfish/hk2" +
      "/xml/test/pbuf/pc2/TypeBean.proto\"s\n\024PBu" +
      "fPrecompileChild2\022\016\n\006z_type\030\001 \001(\010\022\r\n\005bty" +
      "pe\030\002 \001(\005\022<\n\005types\030\003 \001(\0132-.org.glassfish." +
      "hk2.xml.test.pbuf.pc2.TypeBeanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.getDescriptor(),
        }, assigner);
    internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_glassfish_hk2_xml_test_pbuf_pc2_PBufPrecompileChild2_descriptor,
        new java.lang.String[] { "ZType", "Btype", "Types", });
    org.glassfish.hk2.xml.test.pbuf.pc2.TypeBeanOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
