DROP TABLE SUPPLIERS;
DROP TABLE PARTS;

CREATE TABLE PARTS (
    PARTID INT PRIMARY KEY,
    NAME   VARCHAR(15),
    COLOR  VARCHAR(20),
    WEIGHT INT,
    PRICE  FLOAT
) ENGINE=INNODB;

CREATE TABLE SUPPLIERS (
    PARTID     INT NOT NULL REFERENCES PARTS(PARTID),
    SUPPLIERID INT,
    NAME       VARCHAR(15), 
    STATUS     INT,
    CITY       VARCHAR(50),
    CONSTRAINT PK_SUPPLIERS primary key(SUPPLIERID, PARTID)
) ENGINE=INNODB;

COMMIT;

quit;
