DROP TABLE UNKNOWNPK1 cascade;
DROP TABLE UNKNOWNPK2 cascade;

CREATE TABLE UNKNOWNPK1
(
    ID     DECIMAL(38)          PRIMARY KEY,
    NAME   VARCHAR(32) NULL
) ;

CREATE TABLE UNKNOWNPK2
(
    ID     DECIMAL(38)          PRIMARY KEY,
    NAME   VARCHAR(32) NULL
) ;

commit;

quit;
