DROP TABLE UNKNOWNPK1;
DROP TABLE UNKNOWNPK2;

CREATE TABLE UNKNOWNPK1
(
    id     NUMERIC(30)          PRIMARY KEY NOT NULL,
    name   VARCHAR(32)
);

CREATE TABLE UNKNOWNPK2
(
    id     NUMERIC(30)          PRIMARY KEY NOT NULL,
    name   VARCHAR(32)
);
