DROP TABLE UNKNOWNPK1
DROP TABLE UNKNOWNPK2
go

CREATE TABLE UNKNOWNPK1
(
    ID     NUMERIC(38)          PRIMARY KEY NOT NULL,
    NAME   VARCHAR(32) NULL
)

CREATE TABLE UNKNOWNPK2
(
    ID     NUMERIC(38)          PRIMARY KEY NOT NULL,
    NAME   VARCHAR(32) NULL
)
go
