                <sc:subMenu value="View">
                    <sc:menuItem value="Site Map"/>
                    <sc:menuItem value="Bookmarkable URL"/>
                </sc:subMenu>
                <sc:subMenu value="Tools">
                    <sc:menuItem value="Performance Advisor"/>
                    <sc:menuItem value="User Settings"/>
                    <sc:menuItem value="Update Center"/>
                </sc:subMenu>
                <sc:subMenu value="Monitor">
                    <sc:menuItem value="Configure Monitoring"/>
                    <sc:menuItem value="Web Service"/>
                    <sc:menuItem value="Call Flow"/>
                    <sc:menuItem value="Dashboard"/>
                </sc:subMenu>
                <sc:subMenu value="Bookmarks">
                    <sc:menuItem value="Bookmark This Page"/>
                    <sc:menuItem value="Manage Bookmarks"/>
                    <sc:menuItem value="Common Tasks Page"/>
                </sc:subMenu>
                <sc:subMenu value="Help">
                    <sc:menuItem value="Online Help"/>
                    <sc:menuItem value="Support"/>
                    <sc:menuItem value="Forums"/>
                    <sc:menuItem value="Report a Problem"/>
                    <sc:menuItem value="Register"/>
                    <sc:menuItem value="About Plugins..."/>
                    <sc:menuItem value="About..."/>
                </sc:subMenu>