// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/glassfish/hk2/xml/test/pbuf/pc1/ThingBean.proto

package org.glassfish.hk2.xml.test.pbuf.pc1;

public final class ThingBeanOuterClass {
  private ThingBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ThingBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean}
   */
  public  static final class ThingBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean)
      ThingBeanOrBuilder {
    // Use ThingBean.newBuilder() to construct.
    private ThingBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThingBean() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ThingBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.class, org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean)) {
        return super.equals(obj);
      }
      org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean other = (org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean)
        org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.class, org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.Builder.class);
      }

      // Construct using org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_descriptor;
      }

      public org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean getDefaultInstanceForType() {
        return org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.getDefaultInstance();
      }

      public org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean build() {
        org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean buildPartial() {
        org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean result = new org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean) {
          return mergeFrom((org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean other) {
        if (other == org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean)
    }

    // @@protoc_insertion_point(class_scope:org.glassfish.hk2.xml.test.pbuf.pc1.ThingBean)
    private static final org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean();
    }

    public static org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ThingBean>
        PARSER = new com.google.protobuf.AbstractParser<ThingBean>() {
      public ThingBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ThingBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThingBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ThingBean> getParserForType() {
      return PARSER;
    }

    public org.glassfish.hk2.xml.test.pbuf.pc1.ThingBeanOuterClass.ThingBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3org/glassfish/hk2/xml/test/pbuf/pc1/Th" +
      "ingBean.proto\022#org.glassfish.hk2.xml.tes" +
      "t.pbuf.pc1\"\013\n\tThingBeanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_glassfish_hk2_xml_test_pbuf_pc1_ThingBean_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
