DROP TABLE ONLYGETCONNECTION;
CREATE TABLE ONLYGETCONNECTION(
    name char(20), 
    num integer
);

INSERT INTO ONLYGETCONNECTION values ('abcd', 120);
INSERT INTO ONLYGETCONNECTION values ('pqrs', 220);
