<?xml version="1.0" encoding="UTF-8"?>

<definitions
        name="NamespaceToPackageTest"
	targetNamespace="http://ns2package.org/firstimport/FirstImport.wsdl"
	xmlns:tns="http://ns2package.org/firstimport/FirstImport.wsdl"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ns1="http://ns2package.org/secondimport/types">

  <types>
    <xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://ns2package.org/secondimport/types" schemaLocation="SecondImport.xsd"/>
    </xs:schema>
  </types>

  <message name="Test1Request">
    <part name="params" element="ns1:Test1Request"/>
  </message>
  
  <message name="Test1Response">
    <part name="result" element="ns1:Test1Response"/>
  </message>  
  
  <portType name="Test">
    <operation name="test1">
      <input message="tns:Test1Request"/>
      <output message="tns:Test1Response"/>
    </operation>  
  </portType>
  
  <binding name="TestBinding" type="tns:Test">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="test1">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>      
  </binding>

</definitions>
