<?xml version="1.0" encoding="UTF-8"?>

<definitions
    name="NamespaceToPackageTest"
    targetNamespace="http://ns2package.org/ns2package.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:mts1="http://ns2package.org/firstimport/FirstImport.wsdl"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

  <import
     namespace="http://ns2package.org/firstimport/FirstImport.wsdl"
     location="FirstImport.wsdl"/>

  <types/>

  <service name="TestService">
    <port name="TestPort" binding="mts1:TestBinding">
      <soap:address location="http://test.org/test"/>
    </port>
  </service>

</definitions>
