
package cascadeDelete;

import javax.ejb.*;

/**
 * Created Dec 23, 2002 12:43:06 PM
 * Code generated by the Forte For Java EJB Builder
 * @author mvatkina
 */


public abstract class BBean implements javax.ejb.EntityBean {
    
    private javax.ejb.EntityContext context;
    private boolean cascadeDeleteFromA = false;
    private boolean cascadeDeleteFromC = false;
    
    
    /**
     * @see javax.ejb.EntityBean#setEntityContext(javax.ejb.EntityContext)
     */
    public void setEntityContext(javax.ejb.EntityContext aContext) {
        context=aContext;
    }
    
    
    /**
     * @see javax.ejb.EntityBean#ejbActivate()
     */
    public void ejbActivate() {
        
    }
    
    
    /**
     * @see javax.ejb.EntityBean#ejbPassivate()
     */
    public void ejbPassivate() {
        
    }
    
    
    /**
     * @see javax.ejb.EntityBean#ejbRemove()
     */
    public void ejbRemove() {
        System.out.println("Debug: B ejbRemove");
        cascadeDelete.LocalA a = getA();
        System.out.println("A: " + ((a==null)? "null" : a.getName()));
        
        cascadeDelete.LocalC c = getC();
        System.out.println("C: " + ((c==null)? "null" : c.getName()));

        if (cascadeDeleteFromC && (c != null) )
            throw new EJBException("In B - getC() not NULL in CascadeDeleteFromC!");

        if (cascadeDeleteFromA) {
            if( a != null ) {
                throw new EJBException("In B - getA() not NULL in CascadeDeleteFromA!");

            } else if (c != null) {
                c.cascadeDeleteFromA();
                c.cascadeDeleteFromB();
            }
        }

        System.out.println("Ds: " + getDs().size());
        
        
    }
    
    
    /**
     * @see javax.ejb.EntityBean#unsetEntityContext()
     */
    public void unsetEntityContext() {
        context=null;
    }
    
    
    /**
     * @see javax.ejb.EntityBean#ejbLoad()
     */
    public void ejbLoad() {
        cascadeDeleteFromA = false;
        cascadeDeleteFromC = false;
        
    }
    
    
    /**
     * @see javax.ejb.EntityBean#ejbStore()
     */
    public void ejbStore() {
        
    }
    
    public abstract java.lang.Integer getId();
    public abstract void setId(java.lang.Integer id);
    
    public abstract java.lang.String getName();
    public abstract void setName(java.lang.String name);
    
    public abstract java.util.Collection getDs();
    
    public abstract void setDs(java.util.Collection ds);
    
    public abstract cascadeDelete.LocalC getC();
    
    public abstract void setC(cascadeDelete.LocalC c);
    
    public abstract cascadeDelete.LocalA getA();
    
    public abstract void setA(cascadeDelete.LocalA a);
    
    public java.lang.Integer ejbCreate(java.lang.Integer id, java.lang.String name) throws javax.ejb.CreateException {
        setId(id);
        setName(name);
        return null;
    }
    
    public void ejbPostCreate(java.lang.Integer id, java.lang.String name) throws javax.ejb.CreateException {
    }

    public void cascadeDeleteFromA() {
        cascadeDeleteFromA = true;
    }
    
    public void cascadeDeleteFromC() {
        cascadeDeleteFromC = true;
    }
    
}
