
package cascadeDelete;

import javax.ejb.*;

/**
 * Created Dec 23, 2002 12:43:03 PM
 * Code generated by the Forte For Java EJB Builder
 * @author mvatkina
 */

public interface D extends javax.ejb.EJBObject {
    
}

