
package cascadeDelete;

import javax.ejb.*;

/**
 * Created Dec 23, 2002 12:43:06 PM
 * Code generated by the Forte For Java EJB Builder
 * @author mvatkina
 */

public interface LocalB extends javax.ejb.EJBLocalObject {
    
    public java.lang.Integer getId();
    
    public void setC(cascadeDelete.LocalC c);
    
    public java.util.Collection getDs();
    
    public String getName();

    public void cascadeDeleteFromA();
    
    public void cascadeDeleteFromC();
    
}

