ALTER TABLE DEPARTMENT DROP CONSTRAINT FK_DEPT_2
go
DROP TABLE PRIMITIVE_TYPES
go
DROP TABLE REVIEW
go
DROP TABLE PROJECTPERSON
go
DROP TABLE PROJECT
go
DROP TABLE INSURANCE
go
DROP TABLE PERSON
go
DROP TABLE DEPARTMENT
go
DROP TABLE COMPANY
go

CREATE TABLE COMPANY
(
    COMPANYID INT PRIMARY KEY    NOT NULL,
    NAME      VARCHAR(32)        NULL,
    FOUNDED   DATETIME           NULL,
    ADDRESS   VARCHAR(100)
)
go

CREATE TABLE DEPARTMENT
(
    DEPTID          INT PRIMARY KEY  NOT NULL,
    NAME            VARCHAR(32)      NULL,
    COMPANYID       INT              NULL,
    EMPLOYEEOFMONTH INT              NULL,
    CONSTRAINT FK_DEPT_1 FOREIGN KEY (COMPANYID) REFERENCES COMPANY (COMPANYID)
)
go

CREATE TABLE PERSON
(
    PERSONID      INT PRIMARY KEY     NOT NULL,
    DISCRIMINATOR CHAR(1)             NOT NULL,
    FIRSTNAME     VARCHAR(32)         NULL,
    LASTNAME      VARCHAR(32)         NULL,
    MIDDLENAME    VARCHAR(32)         NULL,
    BIRTHDATE     DATETIME            NULL,
    ADDRESS       VARCHAR(100)        NULL,
    HIREDATE      DATETIME            NULL,
    WEEKLYHOURS   FLOAT               NOT NULL,
    DEPTID        INT                 NULL,
    FUNDINGDEPTID INT                 NULL,
    MGRID         INT                 NULL,
    MENTORID      INT                 NULL,
    HRADVISORID   INT                 NULL,
    WAGE          FLOAT               NULL,
    SALARY        FLOAT               NULL,
    CONSTRAINT FK_PERS_1 FOREIGN KEY (DEPTID)        REFERENCES DEPARTMENT (DEPTID),
    CONSTRAINT FK_PERS_2 FOREIGN KEY (FUNDINGDEPTID) REFERENCES DEPARTMENT (DEPTID),
    CONSTRAINT FK_PERS_3 FOREIGN KEY (MGRID)         REFERENCES PERSON (PERSONID),
    CONSTRAINT FK_PERS_4 FOREIGN KEY (MENTORID)      REFERENCES PERSON (PERSONID),
    CONSTRAINT FK_PERS_5 FOREIGN KEY (HRADVISORID)   REFERENCES PERSON (PERSONID),
    CONSTRAINT UK_PERS_1 UNIQUE(MENTORID)
)
go

ALTER TABLE DEPARTMENT 
    ADD CONSTRAINT FK_DEPT_2 FOREIGN KEY (EMPLOYEEOFMONTH) REFERENCES PERSON (PERSONID)
go

CREATE TABLE INSURANCE
(
    INSID                INT PRIMARY KEY   NOT NULL, 
    DISCRIMINATOR        CHAR(1)           NOT NULL,
    CARRIER              VARCHAR(32)       NULL,
    PERSONID             INT               NULL,
    PLANTYPE             CHAR(3)           NULL,
    LIFETIMEORTHOBENEFIT FLOAT             NULL,
    CONSTRAINT FK_INS_1 FOREIGN KEY (PERSONID) REFERENCES PERSON (PERSONID),
    CONSTRAINT UK_INS_1 UNIQUE (PERSONID)
)
go

CREATE TABLE PROJECT
(
    PROJID INT PRIMARY KEY  NOT NULL,
    NAME   VARCHAR(32)      NULL,
    BUDGET DECIMAL(15,2)    NULL        
)
go

CREATE TABLE PROJECTPERSON
(
    PROJID   INT            NOT NULL,  
    PERSONID INT            NOT NULL,
    CONSTRAINT FK_PRJPERS_1 FOREIGN KEY (PROJID) REFERENCES PROJECT (PROJID),
    CONSTRAINT FK_PRJPERS_2 FOREIGN KEY (PERSONID) REFERENCES PERSON (PERSONID)
)
go

CREATE TABLE REVIEW
(
    PROJID   INT           NOT NULL,
    PERSONID INT           NOT NULL,
    CONSTRAINT FK_REVIEW_1 FOREIGN KEY (PROJID) REFERENCES PROJECT (PROJID),
    CONSTRAINT FK_REVIEW_2 FOREIGN KEY (PERSONID) REFERENCES PERSON (PERSONID)
)
go

CREATE TABLE PRIMITIVE_TYPES
(
    ID               INT PRIMARY KEY      NOT NULL,
    BOOLEAN_NOT_NULL BIT                  NOT NULL,
    BOOLEAN_NULL     TINYINT              NULL,
    BYTE_NOT_NULL    SMALLINT /*TINYINT*/ NOT NULL,
    BYTE_NULL        SMALLINT /*TINYINT*/ NULL,
    SHORT_NOT_NULL   SMALLINT             NOT NULL,
    SHORT_NULL       SMALLINT             NULL,
    INT_NOT_NULL     INT                  NOT NULL,
    INT_NULL         INT                  NULL,
    LONG_NOT_NULL    DECIMAL(20)          NOT NULL,
    LONG_NULL        DECIMAL(20)          NULL,
    FLOAT_NOT_NULL   FLOAT                NOT NULL,
    FLOAT_NULL       FLOAT                NULL,
    DOUBLE_NOT_NULL  DOUBLE PRECISION     NOT NULL,
    DOUBLE_NULL      DOUBLE PRECISION     NULL,
    CHAR_NOT_NULL    CHAR                 NOT NULL,
    CHAR_NULL        CHAR                 NULL,
    DATE_NULL        DATETIME             NULL,
    STRING_NULL      VARCHAR(100)         NULL,
    BIG_DECIMAL      DECIMAL(30,10)       NULL,
    BIG_INTEGER      DECIMAL(30)          NULL,
    PRIMITIVE_TYPES  INT                  NULL
)
go

COMMIT
go
