CREATE TABLE EJB30_HELLO_SESSION3_PERSON (
NAME VARCHAR(256) NOT NULL PRIMARY KEY, ADDRESS VARCHAR(256)
)
;

CREATE TABLE EJB30_HELLO_SESSION3_PERSON_EJB30_HELLO_SESSION3_EMAIL(
NAME VARCHAR(256) NOT NULL, ADDRESS VARCHAR(256) NOT NULL
);
