({
	'bold': 'Bold',
	'copy': 'Copy',
	'cut': 'Cut',
	'delete': 'Delete',
	'indent': 'Indent',
	'inserthorizontalrule': 'Horizental Rule',
	'insertorderedlist': 'Numbered List',
	'insertunorderedlist': 'Bullet List',
	'italic': 'Italic',
	'justifycenter': 'Align Center',
	'justifyfull': 'Justify',
	'justifyleft': 'Align Left',
	'justifyright': 'Align Right',
	'outdent': 'Outdent',
	'paste': 'Paste',
	'redo': 'Redo',
	'removeformat': 'Remove Format',
	'selectall': 'Select All',
	'strikethrough': 'Strikethrough',
	'subscript': 'Subscript',
	'superscript': 'Superscript',
	'underline': 'Underline',
	'undo': 'Undo',
	'unlink': 'Remove Link',
	'createlink': 'Create Link',
	'insertimage': 'Insert Image',
	'htmltoggle': 'HTML Source',
	'forecolor': 'Foreground Color',
	'hilitecolor': 'Background Color',
	'plainformatblock': 'Paragraph Style',
	'formatblock': 'Paragraph Style',
	'fontsize': 'Font Size',
	'fontname': 'Font Name'
})
