
package Data;

import javax.ejb.*;

/**
 * Created Dec 16, 2002 1:22:14 PM
 * Code generated by the Forte For Java EJB Builder
 * @author mvatkina
 */

public interface LocalParts extends javax.ejb.EJBLocalObject {
    
    public void addSupplier(Data.LocalSuppliers supplier);
    
    public void dropSupplier(Data.LocalSuppliers supplier);
    
    public java.lang.String getName();
    
    public void testInCascadeDelete();
    
}

