CREATE TABLE EJB32_PERSISTENCE_CONTEXT_PERSON (
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(256) NOT NULL);

INSERT INTO EJB32_PERSISTENCE_CONTEXT_PERSON (id, name) VALUES (1, 'Tom');
INSERT INTO EJB32_PERSISTENCE_CONTEXT_PERSON (id, name) VALUES (2, 'Lucy');

