DROP TRIGGER T_UNKNOWNPKVC1;
DROP TRIGGER T_UNKNOWNPKVC2;

DROP TABLE UNKNOWNPKVC1;
DROP TABLE UNKNOWNPKVC2;

CREATE TABLE UNKNOWNPKVC1
(
    ID     DECIMAL(38)          	PRIMARY KEY,
    NAME   VARCHAR(32) 	NULL,
    VERSION   DECIMAL(19)  	NOT NULL
) engine=InnoDB;

CREATE TABLE UNKNOWNPKVC2
(
    ID     DECIMAL(38)          	PRIMARY KEY,
    NAME   VARCHAR(32) 	NULL,
    VERSION   DECIMAL(19)  	NOT NULL
) engine=InnoDB;

commit;

CREATE TRIGGER T_UNKNOWNPKVC1
    BEFORE UPDATE ON UNKNOWNPKVC1
    FOR EACH ROW
       SET NEW.VERSION = OLD.VERSION + 1
;

CREATE TRIGGER T_UNKNOWNPKVC2
    BEFORE UPDATE ON UNKNOWNPKVC2
    FOR EACH ROW
       SET NEW.VERSION = OLD.VERSION + 1
;

commit;

quit;
