#!/bin/sh

#
# Copyright 1997-2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

AS_INSTALL=`dirname $0`/..
AS_INSTALL_LIB=$AS_INSTALL/modules
JSP_IMPL=$AS_INSTALL_LIB/@JSP_IMPL@
EL_IMPL=$AS_INSTALL_LIB/@EL_IMPL@
JSTL_IMPL=$AS_INSTALL_LIB/web/@JSTL_IMPL@
JSF_IMPL=$AS_INSTALL_LIB/web/@JSF_IMPL@

java -cp "$AS_INSTALL_LIB/webservices.jar:$AS_INSTALL_LIB/jaxb.jar" com.sun.tools.jxc.SchemaGeneratorFacade "$@"
