DROP TABLE UNKNOWNPK1;
DROP TABLE UNKNOWNPK2;

CREATE TABLE UNKNOWNPK1
(
    id     NUMBER(38)          PRIMARY KEY,
    name   VARCHAR2(32) NULL
);

CREATE TABLE UNKNOWNPK2
(
    id     NUMBER(38)          PRIMARY KEY,
    name   VARCHAR2(32) NULL
);

commit;

quit;
