DROP TABLE USER_TABLE;
DROP TABLE USER_TABLE_BASE64;
DROP TABLE USER_TABLE_HEX;

DROP TABLE USER_TABLE_MD2_BASE64;
DROP TABLE USER_TABLE_MD5_BASE64;
DROP TABLE USER_TABLE_SHA_BASE64;
DROP TABLE USER_TABLE_SHA256_BASE64;
DROP TABLE USER_TABLE_SHA384_BASE64;
DROP TABLE USER_TABLE_SHA512_BASE64;

DROP TABLE USER_TABLE_MD2_HEX;
DROP TABLE USER_TABLE_MD5_HEX;
DROP TABLE USER_TABLE_SHA_HEX;
DROP TABLE USER_TABLE_SHA256_HEX;
DROP TABLE USER_TABLE_SHA384_HEX;
DROP TABLE USER_TABLE_SHA512_HEX;

DROP TABLE GROUP_TABLE;
