/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.
 * 
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common Development
 * and Distribution License("CDDL") (collectively, the "License").  You
 * may not use this file except in compliance with the License. You can obtain
 * a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
 * or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
 * language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each
 * file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 * Sun designates this particular file as subject to the "Classpath" exception
 * as provided by Sun in the GPL Version 2 section of the License file that
 * accompanied this code.  If applicable, add the following below the License
 * Header, with the fields enclosed by brackets [] replaced by your own
 * identifying information: "Portions Copyrighted [year]
 * [name of copyright owner]"
 * 
 * Contributor(s):
 * 
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding "[Contributor]
 * elects to include this software in this distribution under the [CDDL or GPL
 * Version 2] license."  If you don't indicate a single choice of license, a
 * recipient has the option to distribute your version of this file under
 * either the CDDL, the GPL Version 2 or to extend the choice of license to
 * its licensees as provided above.  However, if you add GPL Version 2 code
 * and therefore, elected the GPL Version 2 license, then the option applies
 * only if the new code is made subject to such option by the copyright
 * holder.
 */

/**
* AlternateIIOPAddressComponent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from iorintsockfact.idl and then modified by hand for package
* name, equals and toString.
* Tuesday, July 23, 2002 11:08:46 AM PDT
*/

package com.sun.enterprise.iiop;

public final class AlternateIIOPAddressComponent implements org.omg.CORBA.portable.IDLEntity
{
  public static final int TAG_ALTERNATE_IIOP_ADDRESS_ID = 89374;
  public final String host;
  public final short port;

  public AlternateIIOPAddressComponent ()
  {
    host = null;
    port = 0;
  } // ctor

  public AlternateIIOPAddressComponent (String _host, short _port)
  {
    host = _host;
    port = _port;
  } // ctor

        public int
    hashCode() {
        return super.hashCode() ^ (host == null ? 0 : host.hashCode()) ^ port;
    }
    
    public boolean equals(Object o)
    {
        if (o == null) {
            return false;
        }
        if (! (o instanceof AlternateIIOPAddressComponent)) {
            return false;
        }
        AlternateIIOPAddressComponent other = (AlternateIIOPAddressComponent)o;
        if (other.port != port) {
            return false;
        }
        if (! other.host.equals(host)) {
            return false;
        }
        return true;
    }

    public String toString()
    {
        return "AlternateIIOPAddressComponent[" + host + " " + port + "]";
    }

} // class AlternateIIOPAddressComponent
