<?xml version="1.0" encoding="UTF-8"?>

<definitions name="FindInterest" targetNamespace="http://hello.org/wsdl" xmlns:tns="http://hello.org/wsdl" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<types>
    <xsd:schema>
      <xsd:import namespace="http://hello.org/wsdl" schemaLocation="FindInterest_Schema.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
    </xsd:schema>
  </types>

  <message name="calculateInterest">
    <part name="parameters" element="tns:calculateInterest"/>
  </message>
  <portType name="InterestIF">
    <operation name="calculateInterest">
      <input message="tns:calculateInterest"/></operation></portType>
  <binding name="InterestIFBinding" type="tns:InterestIF">
    <operation name="calculateInterest">
      <input>
        <soap:body  use="literal" namespace="http://hello.org/wsdl"/></input>
      <soap:operation soapAction="urn:calculateInterest"/></operation>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/></binding>
  <service name="FindInterest">
    <port name="InterestIFPort" binding="tns:InterestIFBinding">
      <soap:address location="http://localhost:12013/InterestIFPort"/></port></service></definitions>
