<?xml version="1.0" encoding="utf-8"?>

<!--
	September 14, 2002

	(c) Copyright 2002, The Web Services-Interoperability Organization (WS-I)
	Download or use of this file is governed by the Policies and Bylaws of WS-I.

	For more information, send email info@ws-i.org. 	
-->

<wsdl:definitions 
   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
   xmlns:configurationType="http://www.ws-i.org/SampleApplications/SupplyChainManagement/2002-08/Configuration.xsd" 
   targetNamespace="http://www.ws-i.org/SampleApplications/SupplyChainManagement/2002-08/Configuration.wsdl" 
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
	<wsdl:documentation>
      This WSDL document describes the configuration header to be used by all services except the Logger. This header
      is part of a supply chain management system. It is used to demonstrate a web service that is
      conformant with the Basic Profile and to show how different web service platforms can interoperate.
      </wsdl:documentation>

	<wsdl:types>
		<xs:schema>
			<xs:import namespace="http://www.ws-i.org/SampleApplications/SupplyChainManagement/2002-08/Configuration.xsd" schemaLocation="Configuration.xsd"/>
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="ConfigurationFaultMessage">
	 <wsdl:documentation>
        The Configuration fault header indicates why the configuration was invalid and enumerates all
        of the service URLs which were not valid in Configuration header of the request message.
       </wsdl:documentation>
		<wsdl:part name="ConfigurationFault" element="configurationType:ConfigurationFault"/>
	</wsdl:message>

</wsdl:definitions>
